name: visiovox
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip=24.0
  - cuda-toolkit=12.4
  - pip:
    - torch==2.6.0+cu124 --index-url https://download.pytorch.org/whl/cu124
    - torchvision==0.21.0+cu124 --index-url https://download.pytorch.org/whl/cu124
    - torchaudio==2.6.0+cu124 --index-url https://download.pytorch.org/whl/cu124
    - librosa==0.11.0
    - soundfile==0.13.1
    - opencv-python==4.13.0.92
    - ffmpeg-python==0.2.0
    - numpy==2.4.4
    - pandas==3.0.3
    - tqdm==4.67.3
    - scikit-learn==1.8.0
    - mir_eval==0.8.2
    - openai-whisper==20250625
    - fastapi==0.136.1
    - uvicorn==0.47.0
    - pydantic==2.13.4
    - python-multipart==0.0.28
    - scipy==1.17.1